### ISSUE TITLE
Kravnummer bør være sekvensielt økede gjennom hele dokumentet

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#1]
RST-utgaven har fått kravnummer som starter på 1 i hver liste over krav.

**Comment by AnnKnu** [comment]
Ja det må fikses

**Comment by petterreinholdtsen** [comment]
Hvem tar seg av dette, og når kan det være fikset?

**Comment by petterreinholdtsen** [comment]
På dagens møte sa Mona at hun tar denne og håper å være ferdig i løpet av denne eller neste uke.  Fant ikke github-bruker, sa får ikke tildelt saken til riktig bruker.

**Comment by AnnKnu** [comment]
oppdatert krav nummerering

**Comment by petterreinholdtsen** [comment]
Det ser ut til at det gjenstår endel i kapittel 2?

**Comment by AnnKnu** [comment]
ser det nå. Rart trodde jeg hadde gjort hele kapittel 2..
