### ISSUE TITLE
Finn ut hvorfor github ikke lenger gjenkjenner 030-noark-5-datamodell.rst som RST

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#12]
En eller annen gang mellom endring ff8a536c8add8dd71a214e2c49f49ca47154f3ef og
88655b13aba9322b4bdf82cd011c8de7cc51af10 (jeg mistenker denne endringen trigget det), sluttet Github å kjenne igjen 030-noark-5-datamodell.rst som RST.  Jeg har forsøkt å ryddde i formatteringen, uten at jeg har funnet ut hva konkret som gjorde utslaget.  Klarer ikke se noe konkret galt med endringen selv, men kanskje noen andre ser hva som skapte problemet?

**Comment by petterreinholdtsen** [comment]
Jeg tror jeg klarte å finne feilen.  Det er feil rekkefølge på overskriftsmarkørene.  Ved å bruke `rst2html kapitler/030-noark-5-datamodell.rst` får jeg beskjed om at det er et fatalt problem med filen.

```
kapitler/030-noark-5-datamodell.rst:615: (SEVERE/4) Title level inconsistent:

Skjerming
~~~~~~~~~
Exiting due to level-4 (SEVERE) system message.
```

Ved å kjøre `egrep '^[-=*~]{3}' kapitler/030-noark-5-datamodell.rst ` ser jeg at 
filen starter med overskriftmarkør ===, så ---, deretter *** etterfulgt av ---, så RST så tolker som de fire overskriftsnivåene.  Dette er ikke i tråd med anbefalingen i #5. Problemet oppstår når en kommer til overskriften "Skjerming", som er ~~~ som følger etter ---.  Jeg mistenker løsningen er å endre overskriftene forran tabellene til tabell-beskrivelser og overskriftene foran figurene til figurbeskrivelser.  Hva tror du, @AnnKnu?

**Comment by petterreinholdtsen** [comment]
Se https://stackoverflow.com/questions/53191945/how-can-i-add-a-caption-to-a-restructuredtext-table for informatjon om hvordan tabeller kan få tabelltittel.  Merk at #13 gjelder samme problem som beskrevet her.

**Comment by AnnKnu** [comment]
@petterreinholdtsen du kan ha rett i det at det er tabell overskriftene som har skapt problemet. Kan være lurt å endre til tabell tittel.

**Comment by petterreinholdtsen** [comment]
Titler og tabeller er endret, og github kjenner nå igjen filen som RST.  Det viste seg effektivt å bruke rst2html for å finne formatfeil, og når de feilene som ble rapportert av rst2html var fikset så var github igjen i stand til å vise frem RST-filen.
