### ISSUE TITLE
Overordnet innspill til endring av Noark-standarden

### ISSUE THREAD

**Issue by jeancaquet** [arkivverket/noark5-standard#121]
Hei! 

I Documaster har vi i den senere tid jobbet med integrasjoner og arkiveringer fra flere forskjellige systemer hvor vi har tatt utgangspunkt i standardens iboende fleksibilitet. Det vi har oppdaget i prosessen er at standarden ikke bare kan brukes som den er i de aller fleste tilfeller, men at den også kan være utgangspunkt til veldig gode arkiver dersom man gjør denne jobben ordentlig. Men det er enkelte generelle “oppmykninger” som kan gjøre standarden bedre og vi legger ut våre observasjoner her (også på oppfordring fra Riksarkivet) i håp om at vi kan få en god og livlig debatt av dette.  

Hovedfokuset vårt har vært å gjøre standarden mer fleksibel, mer forståelig, og mer konsistent. Vi kan gå mer i detalj på metadatanivå, men det et det overordnede vi ønsker å fokusere på. Vi har derfor følgende seks hovedpunkter. 

- Klassifikasjon 
- Partsforhold 
- Statusfelter 
- Ta mappe ut av hierarkiet 
- Tillate VSM (virksomhetsspesifikke metadata) på alle nivåer 
- Skille arkiv/journalføring 

**Klassifikasjon**
Klassifikasjon er vårt beste virkemiddel for å legge til rette for gjenbruk av dataene. Klassifikasjon i Noark har mye arv fra den gang arkivkoden var laget for gjenfinning i et papirarkiv og bør oppdateres til å passe et digitalt miljø. Vi ser konkrete forbedringsmuligheter på tre områder: 

- _Fjern skillet mellom primære og sekundære klassifikasjonssystemer_ Å benytte flere klassifikasjonssystemer i parallell vil gjøre underverker for strukturering og gjenfinning. Skillet mellom primære og sekundære klassifikasjonssystemer virker kunstig og kompliserende. Dersom det er behov for oppdeling kan man heller gi dem egenskapene entydig/flertydig, obligatorisk/valgfri. 

- _Tillate klassering på flere nivåer_  Det bør være mulig å benytte klasse på flere nivåer i arkivstrukturen samtidig.  

- _Håndtere andre metadataelementer som klasser_
Dersom man kan håndtere flere av dagens mer spesialiserte metadataelementer som klasser, vil man også oppnå mye større fleksibilitet i standarden. Eksempler på denne typen metadataelementer kan være «journalførende enhet», «administrativ enhet» og «dokumenttype» fra dagens standard, men også mer spesialiserte data fra andre systemer. 

**Partsforhold** 
‘Sakspart’ og ‘korrespondansepart’ bør endres til spesifikke roller i det nøytrale objektet ‘part’, som kan ha ulike og systemtilpassede roller, uavhengig av hvor den ligger i hierarkiet. Det kunne vært definert et minimums fellessett metadata med informasjon om en person/organisasjon, personens/organisasjonens rolle med mulighet til å utvide med flere metadata. I tillegg kan det være nyttig med muligheten til å beskrive relasjoner partene imellom. 

 **Statusfelter** 
Noark-standarden har en lang rekke statusfelter, som er en arv fra tidligere Noark-standarder. Statusfeltene blir i dag typisk brukt for å finne frem til hvilke saker som er ferdigstilt av saksbehandler og klare for journalføring, eller for å hente ut restanselister. Dette kan være nyttig i en saksbehandlingsløsning, men trenger ikke være definert i en standard for arkiv.  

**Ta mappe ut av hierarkiet** 
Mappe bør gjøres til et valgfritt attributt som kan brukes til å linke registreringer som hører sammen. Dette løser mange eksisterende utfordringer med Noark. 

**Virksomhetsspesifikke metadata på alle nivåer** 
Ved å tillate å knytte VSM til andre nivåer og attributter i arkivstrukturen, kan lage en mer fleksibel standard. Vi har mange gode eksempler på forbedring av arkiver ved f.eks. å knytte VSM til klasse, dokument eller parter (alle typer) 

**Skille arkiv/journalføring** 
Det finnes i dag gode muligheter for å lage spesialiserte mapper ved bruk av VSM. Grunnen til at denne muligheten ikke blir brukt mer, er at hvis et dokument skal ut til offentligheten, må det journalføres og dermed knyttes til en sak. Det burde derfor ses på muligheten til å få et enda klarere skille mellom journalføring og arkivering (noe som også er nevnt i NOUen for ny arkivlov) 

Jean, Petter & Erik - Documaster

**Comment by petterreinholdtsen** [comment]
Forslag til utvidelse av flere entiteter med virksomhetsspesifikkeMetadata er endringsforslag #96 og #100.  Send flere endringsforslag hvis det trengs.

**Comment by jeancaquet** [comment]
Flott! Vet det er tatt opp hundrevis av ganger og har ikke tenkt å gi oss før det blir implementert ;-)

**Comment by petterreinholdtsen** [comment]
[jeancaquet]
> Flott! Vet det er tatt opp hundrevis av ganger og har ikke tenkt å gi
> oss før det blir implementert ;-)

Da anbefaler jeg å lese over mangelmeldingene og endringsforslagene, og
sende inn konkrete beskrivelser av tekstlige endrigner i Noark
5-dokumentet hvis dere har flere ønsker til endringer.  Det øker sjansen
betraktelig for å få endringer inn, og gjør det mulig å finpusse forslag
i fellesskap.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by jeancaquet** [comment]
Men der kom jo forsåvidt den, så da forsvinner vel egentlig bare poenget :-) https://www.arkivverket.no/nyheter/arkivverket-avslutter-utviklingen-av-noark-standarden-copy?fbclid=IwAR2DVsQjJxR8iyTRSV1Hx4n67MNLATrH2CmZ72OAllRyJEPe4mLHgXKrrDc

**Comment by oivkru** [comment]
> Men der kom jo forsåvidt den, så da forsvinner vel egentlig bare poenget :-) https://www.arkivverket.no/nyheter/arkivverket-avslutter-utviklingen-av-noark-standarden-copy?fbclid=IwAR2DVsQjJxR8iyTRSV1Hx4n67MNLATrH2CmZ72OAllRyJEPe4mLHgXKrrDc

Siden det vil finnes system/arkivkjerner basert på Noark 5 i en del år fremover, må vi legge til rette for at disse kan justeres slik at de kan ta imot dokumentasjon uten informasjonstap. Deler/mye av det dere spiller inn over går derfor under kategorien feilrettinger, for det er snakk om justeringer i datamodellen som er nødvendige for å unngå informasjons- og dokumentasjonstap.

**Comment by jeancaquet** [comment]
Ok! Men da lukker jeg tråden siden det var på siden det ikke er en del av diskusjonen.
