### ISSUE TITLE
Feil i overskifter 

### ISSUE THREAD

**Issue by AnnKnu** [arkivverket/noark5-standard#13]
Følgende oppsett er brukt 

Kapittel  ===================

Undernivå 1  ----------

Undernivå 2 ~~~~~~~~~

Undernivå 3 ***********

Men når jeg ser i pdf, så ser det ut til at overskrifter med ****** har blitt undernivå 2, skulle vært undernivå 3 og    ~~~~~~~~~~ som skulle vært undernivå 2 har blitt undernivå 3.   Ser ut til at Kapittel 1 Innledning er korrekt, og feilen starter i kapittel 2 Data modell. 

I tillegg er Overskrift Undernivå 1 er mindre i størrelse enn overskift nivå 3.  (se kapittel 2.2 Metadata)

Vi ønsker ikke nummerering på undernivå 3, kun uthevet og litt større tekst. Undernivå 3 trenger heller ikke være med kapittelvis i innholdsfortegnelsen, men heller  listes ut en oversikt over alle tabellene tilslutt, slik som det er gjort for figurer.

**Comment by petterreinholdtsen** [comment]
Husk at overskriftene uttrykker struktur, ikke tekststørrelse.  I 030-noark-5-datamodell.rst er rekkefølgen slik (i følge `egrep -C1 '^[-=*~]{3}' kapitler/030-noark-5-datamodell.rst`):

```
Noark 5 datamodell
==================

--
Overordnet datamodell
---------------------

--
Overordnede krav til arkivstrukturen
************************************

--
Metadata
--------

--
Overordnede krav til metadata
*****************************
[...]
```
En går altså fra undernivå 1 direkte til undernivå 3.  Det fungerer ikke.

**Comment by AnnKnu** [comment]
fikset i 030-noark-5-datamodell.rst
