### ISSUE TITLE
Krav nr 2.8.3 er registrert to ganger

### ISSUE THREAD

**Issue by AnnKnu** [arkivverket/noark5-standard#14]
![image](https://user-images.githubusercontent.com/43807357/75887021-718da600-5e29-11ea-883e-fb8d519f6578.png)
![image](https://user-images.githubusercontent.com/43807357/75887037-781c1d80-5e29-11ea-900d-d1e08eaef33a.png)

**Comment by petterreinholdtsen** [comment]
De to er etterfulgt av 2.8.4 til og med 2.8.22, så enten må en av 2.8.3-kravene få nummer 2.8.23 eller så må 18 krav bytte nummer.  Hvis nøkkelordkravet skal bytte navn til 2.8.23, så er det kanskje like lurt å flytte den delen av teksten (2.8.2 Nøkkelord) etter 2.8.6 Presedens.

**Comment by hanber** [comment]
Er unntatt registrering noe som henger igjen fra basisregistrering? Hensikten med basisregistrering var at de ikke skulle kunne søkes fram, men bare finnes når man slo opp på mappen. Dette skal være erstattet med _arkivnotat_.

**Comment by petterreinholdtsen** [comment]
Har laget egen mangelmelding #33 for å finne ut av hva '(unntatt registrering)' betyr.

**Comment by oivkru** [comment]
Alternativt ta bort kravet om nøkkelord. Det er et metadataelement, som er beskrevet i metadatakatalogen, og det fremgår av objektsortert metadatakatalog hvor i strukturen det kan være. Unødvendig med et eget krav som sier det samme.

**Comment by petterreinholdtsen** [comment]
[oivkru]
> Alternativt ta bort kravet om nøkkelord. Det er et metadataelement,
> som er beskrevet i metadatakatalogen, og det fremgår av objektsortert
> metadatakatalog hvor i strukturen det kan være. Unødvendig med et eget
> krav som sier det samme.

Jeg må innrømme at jeg har tolket kravlisten som autorativ, mens
metadatakatalog og objektsortert metadatakatalog var mer veiledende.  Ut
fra den forståelsen vil en oppføring i metadatakatalog og objektsortert
metadatakatalog kun være rådgivende uten et tilhørende krav.  Hvis min
forståelse er en misforståelse, burde kanskje rollen og kravstatus for
de to tilleggene forklares nærmere?

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Jeg støtter forslaget om å fjerne kravet, og men vi holder på, foreslår jeg å fjerne avsnittet "Nøkkelord består bare av ett metadataelement: M022 noekkelord, og er derfor ikke definert som et eget objekt men plassert direkte i **tabellene** for de aktuelle arkivenhetene.", for ikke å si noe om implementeringen.

**Comment by oivkru** [comment]
@petterreinholdtsen I innledningen til kapittel 2 i standarden står det: 
_Datamodellene som presenteres i dette dokumentet er en visuell presentasjon av det som fremgår av vedlegg 2 Metadata gruppert på objekter. Hvis det er konflikt mellom den visuelle presentasjonen av objektene og relasjonene mellom dem i dette dokumentet, og det som står i vedlegg 2, er det vedlegg 2 som skal oppfattes som «fasit.»_ 
Krav 2.8.3 er valgfritt, og metadataelementet er valgfritt på klasse, mappe eller registrering. Det virker overflødig å ha et valgfritt krav om at det skal finnes en tjeneste/funksjon som håndterer et valgfritt metadataelement.

**Comment by hanber** [comment]
Enig, men dersom man ikke ser metadataene i sammenheng med kravene, kan det være greit å markere kravet som valgfritt, selv om det blir litt smør på flesk.

**Comment by petterreinholdtsen** [comment]
[Øyvind Kruse]
> @petterreinholdtsen I innledningen til kapittel 2 i standarden står det: 
> _Datamodellene som presenteres i dette dokumentet er en visuell
> presentasjon av det som fremgår av vedlegg 2 Metadata gruppert på
> objekter. Hvis det er konflikt mellom den visuelle presentasjonen av
> objektene og relasjonene mellom dem i dette dokumentet, og det som
> står i vedlegg 2, er det vedlegg 2 som skal oppfattes som «fasit.»_
> Krav 2.8.3 er valgfritt, og metadataelementet er valgfritt på klasse,
> mappe eller registrering. Det virker overflødig å ha et valgfritt krav
> om at det skal finnes en tjeneste/funksjon som håndterer et valgfritt
> metadataelement.

Jeg er enig i at det virker overflødig.  Videre forstår jeg deg dithen
at du leser ut fra de du henviser til fra kapittel 2, at beskrivelsen av
objekter og metadata dithen at alt det som står i tillegg B er krav til
utformingen av objektene i et system utformet i tråd med Noark 5.  Jeg
har ikke lest det på samme vis, delvis basert på første avsnitt i
tillegg B:

  "I denne oversikten blir metadata i Noark 5 gruppert på
  objekter. Tabellene nedenfor er utgangspunktet for XML-skjemaene som
  spesifiserer avleveringsformatet. De fleste objektene nedenfor inngår
  i arkivstrukturen, og skal nøstes inn i én samlet, hierarkisk
  struktur."

Det er spesielt bruken av "er utgangspunkt for" og "de fleste objektene
nedenfor inngår i" som gjør at det er uklart for meg hvilke deler av
tillegg B som er krav og hvilke som ikke er det.

Listen med nummererte krav er derimot mer klart definert som krav og
hver av dem kreves besvart når en søker om godkjenning, mens det ikke er
tilsvarende vurdering opp mot objektbeskrivelsene i tillegg B, sa vidt
meg bekjent.  Det gjør det dermed uklart om disse to delene av
spesifikasjonen har samme status når det gjelder godkjenning.

-- 
Vennlig hilsen
Petter Reinholdtsen
