### ISSUE TITLE
Feil metadata-id i vedlegg 1 og metadata-kort.

### ISSUE THREAD

**Issue by joergen-vs** [arkivverket/noark5-standard#157]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Standard
           Kategori  Noark 5.5.0
 ------------------  ---------------------------------

### Beskrivelse

Det er oppgitt feil metadata-id "to" steder:
https://github.com/arkivverket/noark5-standard/blob/e0cd63a9ed1e907d9b2825492eb7c7f656f24c81/kapitler/110-vedlegg_1_metadatakatalog-auto.rst#L476 (M025's betingelser)
https://github.com/arkivverket/noark5-standard/blob/e0cd63a9ed1e907d9b2825492eb7c7f656f24c81/metadata/M025.yaml#L4

## Ønsket endring

*M502 skjermingMetadata.*

**Comment by petterreinholdtsen** [comment]
[Jørgen]
> Det er oppgitt feil metadata-id "to" steder:
> https://github.com/arkivverket/noark5-standard/blob/e0cd63a9ed1e907d9b2825492eb7c7f656f24c81/kapitler/110-vedlegg_1_metadatakatalog-auto.rst#L476 (M025's betingelser)
> https://github.com/arkivverket/noark5-standard/blob/e0cd63a9ed1e907d9b2825492eb7c7f656f24c81/metadata/M025.yaml#L4

Takk for tipset.  rst-filen er automatisk avledet fra yaml-filene i
metadata/, så ikke overraskende at det er feil begge steder.

Har laget endringsforslag #158 som jeg håper fikser problemet.  Tar det
inn i master om noen dager, med mindre noen oppdager problemer med
forslaget.

-- 
Vennlig hilsen
Petter Reinholdtsen
