### ISSUE TITLE
sett på titler på alle tabeller

### ISSUE THREAD

**Issue by AnnKnu** [arkivverket/noark5-standard#18]

**Comment by petterreinholdtsen** [comment]
Da har jeg omformet tabeller til list-table og oppdatert EDITING.rst med litt informasjon om skriving av tabeller og bygging av PDF.  Tror det kun er tabeller uten titler igjen som grid-table.  Det gjelder spesielt vedleggene.

**Comment by petterreinholdtsen** [comment]
Det viser seg at jeg har tatt feil, list-table *må* ikke ha tittel.  Det er dermed ikke påkrevd å sette titler over alt.

**Comment by AnnKnu** [comment]
@petterreinholdtsen > Det viser seg at jeg har tatt feil, list-table _må_ ikke ha tittel. Det er dermed ikke påkrevd å sette titler over alt.

Da lukker jeg denne
