### ISSUE TITLE
Nevner fortsatt fjernet element 'basisregistrering'

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#19]
Elementet 'basisregistrering' nevnes tre ganger fortsatt, en gang i 030-noark-5-datamodell.rst og to ganger i 130-vedlegg_3_logg_over_endringer.rst.  Elementet ble slått sammen med 'registrering' og bør ikke lenger omtales i Noark 5.

**Comment by hanber** [comment]
Løses i issue #33.
