### ISSUE TITLE
UML-diagram bør endres fra bilder til tekstlig representasjon (PlantUML)

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#2]
For å kunne enklere ta imot endringer av UML-diagrammene så bør de endres til en tekstlig representasjon.  Foreslår [PlantUML](https://plantuml.com/), som også brukes av spesifikasjonen av tjenestegrensesnittet.

**Comment by petterreinholdtsen** [comment]
Jeg har endel spørsmål rundt UML-diagrammene i dagens Noark
5-standarder, som dukket opp i det jeg forsøker å gjenskape de med
plantuml for enklere fremtidig vedlikehold.  Sidetallene henviser til
PDF utgitt i desember:
 * Hvorfor har figuren på side 16 diamantrelasjon uten pil, mens
   tilsvarende figur på side 19 har diamantrelasjon med pil?  Det
   varierer hvilken relasjon som er brukt mellom klassene i
   diagrammene.  Hva skal forskjellen formidle?
 * Hvorfor er noen klasser i grått, mens andre er i lys gul?  Gjelder
   blant andre diagram på side 19, 21, 25, 27 I noen diagrammer er det
   brukt tre farger, grå, gul og gulrød.  Hva skal fargeforskjellen
   formidle?
 * Hvorfor har klasser ulikt innhold i ulike figurer?  Et eksempel er
   'arkiv' på side 19 som har færre felt enn 'arkiv' på side 21.  Har
   det noe med bruken av fet skrift for obligatoriske metadata (jamfør
   forklaring på side 18)?

**Comment by petterreinholdtsen** [comment]
Figurene er også tilgjengelige fra https://github.com/arkivverket/noark5-standard/blob/master/kapitler/media/ .

side 16: image2.png
side 19: image4.jpg
side 21: image5.jpg
side 25: image6.jpg
side 27: image7.jpg

**Comment by petterreinholdtsen** [comment]
Da har jeg laget utkast til PlantUML-filer for alle UML-diagrammene.  De bør kvalitetssikres og noen av dem ble ikke like fine som originalene.

**Comment by petterreinholdtsen** [comment]
Har laget en midlertidig sammenligningsside på
https://github.com/petterreinholdtsen/noark5-standard/blob/plantuml-diagrams/uml-compare.md .  Savner svar på mine spørsmål for å komme i mål med modelleringen.

**Comment by tsodring** [comment]
> Hvorfor har figuren på side 16 diamantrelasjon uten pil, mens
> tilsvarende figur på side 19 har diamantrelasjon med pil? Det
> varierer hvilken relasjon som er brukt mellom klassene i
> diagrammene. Hva skal forskjellen formidle?

Jeg tipper at det er en forglemmelse. Jeg tror ikke det er ment å formidle noe. Noark som konseptuell standard bruker UML, men jeg er usikker hvor streng de er på det.

> Hvorfor er noen klasser i grått, mens andre er i lys gul? Gjelder
> blant andre diagram på side 19, 21, 25, 27 I noen diagrammer er det
> brukt tre farger, grå, gul og gulrød. Hva skal fargeforskjellen
> formidle?

Denne tilnærmingen er brukt i tidligere utgaver av standarden. Jeg tror Arkivverket bruker "gult" for å si det er denne delen av arkivstruktur som vi fokuserer på i dette kapittelet/underkapittelet.  Jeg synes det er også opphavet til at jeg kaller arkivstruktur for primærentiteter, mens det so er grå er det jeg omtaler som sekundærentiteter.

> Hvorfor har klasser ulikt innhold i ulike figurer? Et eksempel er
> 'arkiv' på side 19 som har færre felt enn 'arkiv' på side 21. Har
> det noe med bruken av fet skrift for obligatoriske metadata (jamfør
> forklaring på side 18)?

Jeg tror det er copy/paste som er gått litt galt. Jeg klarer ikke å se noe spesielt grunn til at det er behov å skille med fet skrift.

Jeg tror du bør se bort fra disse tingene og utvikle dine UML tegninger utifra hva som gir mening for en leser.

**Comment by AnnKnu** [comment]
@petterreinholdtsen 
fet indikerer O-krav
ikke fet er OB- eller V-krav
Fargene har en hensikt, eks Gul gjenspeiler hoveddatamodell. etc.

**Comment by petterreinholdtsen** [comment]
Takk for nyttige svar.  Da er manglende piler lagt til i PlantUML-modellene, samt fet/ikke-fet korrigert.  Har også forbedret utlegg på endel av diagrammene.  Gjenstår å finne ut hvilke kategorier de ulike fargene skal knyttes til.  Kanskje de bør modellerers som ulike UML-pakker, for å gjøre det klarere for leseren hva som menes med fargene?

Uansett, sammenlignings-siden nevnt over er oppdatert med de siste diagrammene.

**Comment by petterreinholdtsen** [comment]
Jeg har endret UML-diagramutkastene til å bruke pakker i stedet for fargekoder til å beskrive gruppering av klasser.  Ser det mer opplysende ut?  Gikk for pakkenavnene Fellesfunksjonalitet, Sakarkiv og Møter.

**Comment by petterreinholdtsen** [comment]
På dagens møte kom vi frem til at vi går for PlantUML.  Bruken av pakker er basert på en misforståelse av hva fargene i originalen er ment å formidle, og droppes i første omgang.  Fargene er i følge @hanber ment å indikere hvilke klasser som er i fokus (gule) eller ikke (grå), og hvilke som er avledede (rødlige).  Fargene droppes i første omgang.  Bruken av (C) for å indikere klasser (og ikke for eksempel grensesnitt/interface) droppes, da alt vel er klasser i våre diagrammer.  Vi vurderer om beskrankningene droppes i fremtiden, men beholder dem i første omgang.  @petterreinholdtsen oppdaterer plantuml-filene og tar endret forslag inn i master.
