### ISSUE TITLE
Defekt lenke til godkjenningsordning i innledningen

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#22]
Innledningen lenker til https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/godkjenningsordning-noark5, en adresse som ikke fungerer.

**Comment by monadani** [comment]
Ja, må oppdateres til: https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/godkjenningsordning-noark#!#block-body-3

**Comment by hanber** [comment]
En bagatell, men jeg synes lenken heller burde peke til https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/godkjenningsordning-noark for å få med omgivelsene.

**Comment by petterreinholdtsen** [comment]
Da har vi to forslag til lenker.  Hvem skal avgjøre hvilken av dem som skal brukes, eller om begge skal inn i spesifikasjonen?  Kan vedkommende komme med en konklusjon?

**Comment by AnnKnu** [comment]
Enig med @hanber, bør oppdateres til https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/godkjenningsordning-noark

**Comment by AnnKnu** [comment]
Oppdatert lenke 
https://github.com/arkivverket/noark5-standard/commit/53672d3f869620aaea2b39e6378ba878aac506ca
