### ISSUE TITLE
Hva betyr spørsmål om forgjengere og etterkommere i krav 6.2.2?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#27]
I obligatorisk krav 6.2.2 står følgende:

> En arkivdel skal inneholde referanser til eventuelle forløpere og arvtakere. (forgjengere og etterkommere?)

Hva betyr parantesen?

**Comment by hanber** [comment]
Ingen ting.  Kan fjernes, siden metadataelementene heter referanseForloeper og referanseArvtaker. Vi har hatt som tradisjon å illustrere relasjoner som er representert ved en egenskap (referanse...) med stiplede piler fra objekttypen som inneholder referansen til objekttypen den peker på. Dette mangler i figurene i [https://github.com/arkivverket/noark5-standard/blob/master/kapitler/030-noark-5-datamodell.rst](https://github.com/arkivverket/noark5-standard/blob/master/kapitler/030-noark-5-datamodell.rst).

**Comment by oivkru** [comment]
Kravet kan utgå, dekkes av at det er metadataelementer. Trenger ikke egne krav som sier det samme som metadata.

**Comment by AnnKnu** [comment]
Ref møte 09.11.2020 - Parentesen fjernes

Kun: En arkivdel skal inneholde referanser til eventuelle forløpere og arvtakere.
