### ISSUE TITLE
Hvorfor to punktum i krav 6.4.15?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#28]
Valgfrie krav 6.4.15 ser slik ut i dag:

> Filene i en avleveringspakke skal ligge under en felles overordnet filkatalog kalt **avleveringspakke.**
>     
> Avleveringspakken skal inneholde følgende filer:
>     
> - **arkivuttrekk.xml** (dokumentasjon av innholdet i
>   arkivuttrekket)
> - **arkivstruktur.xml** (metadata om dokumentene)
> - **endringslogg.xml** (logging av endrede metadata)
>
> ..
>
> Dersom avleveringspakken inneholder arkivuttrekk med journalføringspliktig informasjon, skal den i tillegg inneholde følgende filer:
> 
> - **loependeJournal.xml**
> - **offentligJournal.xml**
>
> ..
> 
> XML-skjemaene til alle XML-filer i avleveringspakken skal også være inkludert.  For virksomhetsspesifikke metadata skal det medfølge egne XML-skjemaer.
> 
> Dokumentene skal ligge i en underkatalog kalt **DOKUMENT**. Denne katalogen kan struktureres i nye underkataloger etter fritt valg. Dokumentfilene endelse skal angi arkivformat: **pdf**, **tif**, **txt** osv.

Hva skal de to punktumene formidle?  Skal det være tre punktum som i en ellipse?  Eller en slags strek i tabellcellen?  Eller noe helt annet?

**Comment by AnnKnu** [comment]
Skal slettes

**Comment by AnnKnu** [comment]
fjernet ..
https://github.com/arkivverket/noark5-standard/commit/09d7be13ef4d810212218ca7e62c607cba30ced0
