### ISSUE TITLE
Uklare arkivenheter i tillegg C ("forenklet registrering" og "bevaring og kassasjon")

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#32]
Tabellen i tillegg C lister opp "forenklet registrering" og "bevaring og
kassasjon" i kolonnen for arkivenhet.  Hva menes egentlig med Arkivenhet her?  Jeg trodde dette var objektene listet opp i tillegg B, og hverken "forenklet registrering" eller "bevaring og kassasjon" er listet opp der.  Kan det være at radene bør bytte verdi i disse cellene, for eksempel til "registrering" og "kassasjon"?

**Comment by AnnKnu** [comment]
gjelder metadataelement nr M020, M024 og M208

**Comment by hanber** [comment]
"Forenklet registrering" er en utdatert betegnelse for registrering av en "basisregistrering", og har så vidt jeg vet aldri vært et objekt i arkivstrukturen.
"basisregistrering" er også utdatert og slått sammen med "registrering", slik at i degens standard finnes bare "registrering".
I tabellen under linje 1999 skal derfor både "basisregistrering" og "forenklet registrering" erstattes med "registrering".
Likeledes skal "bevaring og kassasjon", som ikke finnes i arkivstrukturen endres til "kassasjon".

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> "Forenklet registrering" er en utdatert betegnelse for registrering av
> en "basisregistrering", og har så vidt jeg vet aldri vært et objekt i
> arkivstrukturen.  "basisregistrering" er også utdatert og slått sammen
> med "registrering", slik at i degens standard finnes bare
> "registrering".  I tabellen under linje 1999 skal derfor både
> "basisregistrering" og "forenklet registrering" erstattes med
> "registrering".  Likeledes skal "bevaring og kassasjon", som ikke
> finnes i arkivstrukturen endres til "kassasjon".

Høres fornuftig ut.  Men jeg ser ikke at endringen er lagt inn i teksten
i master.  Inntil endringen er på plass er det vel lurt å la denne
mangelmeldingen være åpen, da problemet jo er uløst frem til offisiell
tekst er korrigert?

Når innsjekkmeldingen der dette fikses inneholder en linje med 'Fixes
#32', så vil innsjekkingen automatisk lukke denne mangelmeldingen.  Det
er min foretrukne måte å lukke mangelmeldinger, da det knytter
endringsforslag og mangelmelding sammen i git-historikken.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Aha. Da gjør vi det slik. Jeg ser til og med at Github sier "May be fixed by #81" :-)

Jeg lukker issue #19, siden det omhandler samme sak.
