### ISSUE TITLE
Hva betyr 'unntatt registrering' i krav 2.8.3 for nøkkelord?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#33]
I obligatorisk krav 2.8.3 om nøkkelord (det er to ulike krav med samme nummer, se #14) står følgende:

> Det bør finnes en tjeneste/funksjon for å knytte ett eller flere nøkkelord til klasser, mapper og registreringer (unntatt registrering).

Formuleringen 'og registreringer (unntatt registrering)' er uklar, og samsvarer ikke med beskrivelsen lenger opp som sier at

> Det bør være mulig å føye ett eller flere nøkkelord til en *klasse*, en *mappe* eller en *registrering*.

Bør dette omformuleres?  Mitt beste gjett er at dette er rester fra da basisregistrering og registrering ble slått sammen.

**Comment by oivkru** [comment]
Helt korrekt at dette er rester fra da basisregistrering og registrering ble slått sammen. Var opprinnelig at det ikke skulle være mulig å knytte nøkkelord på den enkleste varianten av registrering.

**Comment by petterreinholdtsen** [comment]
Jeg laget et endringsforslag om å fjerne '(unntatt registrering)', rydding i duplikatkravnummer har jeg ingen ide hvordan best løse.
