### ISSUE TITLE
Savner metadatakatalogoppføring for mimeType

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#35]
Tjenestegrensesnittet har en attributt mimeType koblet til arkivenheten Dokumentobjekt.  Denne bør kunne utvekles tas vare på og utveksles med deponiformatet til Noark 5, og derfor inn i metadatakatalogen.  I følge spesifikasjonen for tjenestegrensesnittet var MIME-type del av Noark 5 under navnet veMimeType.  Jeg foreslår at oppføringen får M-nummer i samme kategori som format og variantFormat, der første ledige er M708.

MIME-typer er beskrevet i IETF RFC 6838, https://tools.ietf.org/html/rfc6838 .  Feltet må være i tekststreng-format med forekomst 0..1, dvs. valgfritt.  Gyldige verdier bør i utgangspunktet hentet fra IANAs register over MIME-typer, https://www.iana.org/assignments/media-types/media-types.xhtml, men bør tillate enhver gyldig MIME-type selv om den ikke er registrert i den offisielle listen over MIME-typer.

Noark 5 må endres i tillegg A og B, samt XSD for å få på plass dette nye feltet.

**Comment by petterreinholdtsen** [comment]
Behovet for dette feltet ble også diskutert i https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/77 .

**Comment by hanber** [comment]
Hva er tillegg A og B?

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Hva er tillegg A og B?

Første og andre tillegg i PDF tilgjengelig fra
<URL: https://github.com/arkivverket/noark5-standard/tree/master/avledet >,
aka metadatakatalogen og metadata gruppert på objekter.

--
Vennlig hilsen
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Jeg finner mimeType omtalt i metakat koblet til GeoIntegrasjon sin
Fil[1] og dokumentobjekt[2] med referanse 'Betaversjon'.  Begge steder
omtaler den som 'veMimeType i n4'.

  [1] <URL: http://arkivverket.metakat.no/Objekttype/Index/EAID_10D58E74_F787_4878_9B52_48BE5E1860FB >
  [2] <URL: http://arkivverket.metakat.no/Objekttype/Index/EAID_A7642A0D_41DB_4b21_9CC7_EFF2C5AE741B

Jeg foreslår at mimeType legges inn i M700-serien for tekniske metadata,
for eksempel som M716 som er først ledige.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Jeg laget utkast til endringsforslag #67 for ny metadatakatalogoppføring for mimeType.  Litt i tvil om YAML-feltene avleveres, betingelser, kilde og kommentar.  Antar den bør være valgfri for å håndtere arkivsystemer som ikke bruker mimeType.

**Comment by petterreinholdtsen** [comment]
Jeg klarte ikke finne ut hva 'veMimeType i n4' henviser til, da 'mimetype' ikke er nevnt i noe Noark 4-relatert under https://github.com/arkivverket/schemas/ og tok den derfor ikke med i tillegg B som Noark 4-feltnavn.

**Comment by petterreinholdtsen** [comment]
Det slår meg at det kanskje bør nevnes at M716 strengt tatt ikke er første ledige, men neste verdi etter største M-verdi i M700-serien.  Det er mange "hull" i serien som jeg antar kommer av at katalogen tidligere hadde metadatatyper som siden er blitt fjernet.  Antar videre at det vil være uheldig å gjenbruke MXXX-verdier og gikk derfor for M716 som jeg antar aldri har vært brukt før i Noark-sammenheng.  Hvis det er ok å "fylle hullene" så kan en i stedet bruke M703 som er laveste ubrukte M-nummer i 700-serien.
