### ISSUE TITLE
Skal M617 avskrivningsdato ha med klokkeslett?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#38]
Det er brukt ulike datatyper for felt M617 avskrivningsdato i tillegg B.  For avskrivning er den oppført som Dato og klokkeslett, mens for journalpost både under loependeJournal og offentligJournal er den oppført som Dato.  I XSD og Tjenestegrensesnitt er den ført opp som dato uten klokkeslett.

Skal disse oppføringene synkroniseres slik at M617 har samme datatype over alt?  I så fall, hvilken datatype skal brukes?

Dette fikser et av problemene rapportert i #24.

**Comment by monadani** [comment]
JA

**Comment by hanber** [comment]
Ja, jeg tror vi har diskutert dette før og blitt enige om at alle skal ha dato og klokkeslett. Der hvor en dato registreres manuelt, bør det i brukergrensesnittet bare fremkomme som en dato, og klokkeslettet skal være 0.

**Comment by petterreinholdtsen** [comment]
Aha.  Da lager jeg et felles endringsforslag der alle får dato og klokkeslett.

**Comment by petterreinholdtsen** [comment]
Bare for å være sikker, når du sier alle skal ha klokkeslett, snakker du om alle tidsstempler, eller all bruk av M617?  Jeg tolket det som alle tidsstempler i endringsforslag #58.  Håper det ble riktig.  Det vil også kreve endringer i XSD for å bytte alle 'date' med 'dateTime', og bør kanskje følges av en tekstlig beskrivelse som sier hvordan klokkeslett skal håndteres når brukergrensesnitt kun spør om dato.

**Comment by tsodring** [comment]
Dette er interessant. Jeg er enig med denne endringen, at Date -> DateTime. Siden en slik utvidelse krever mer informasjon enn før så kan dette ikke ha tilbakevirkende kraft så her bør XSD skjemaer _synces_ med TG. Jeg tror det er et arbeid som uansett må gjøres og er antagelig noe som nikita prosjektet kan teste fram mot neste mindre versjon av tjenestegrensesnittet og Noark standarden.

**Comment by hanber** [comment]
@petterreinholdtsen Det var riktig tolket, gjelder alle tidsstempler.

Når jeg ser på xsd-en til metadatakatalogen, blir jeg litt i tvil, siden det er så mange date-elementer der. Det gjelder alle elementene som heter xxxDato unntatt sendtDato og mottattDato, som er blitte endret fordi det ble ansett relevant når på døgnet dokumenter ble sendt eller mottatt, i tillegg til at tidspunktene alltid er tilgjengelige ved elektronisk utveksling. I automatisk saksbehandling blir tidspunktene viktigere. Siden de i automatisk arkivering også er enklere å håndtere, spiller det ikke så stor rolle om klokkeslett er med selv om det presise tidspunktet har liten betydning. Jeg mener at vi på et tidspunkt anså det som en forenkling at alle tidsstempler fikk samme datatype.

Dette må verifiseres av noen med mer arkivkompetanse enn meg og de som har ansvar for skjemaene og eventuelle problemer med manglende bakoverkompatibilitet.
