### ISSUE TITLE
Tilordne sekundær klassifikasjonsinformasjon M209 også til registrering?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#40]
I dag kan en knytte sekundær klassifikasjonsinformasjon til en saksmappe ved hjelp av M209 referanseSekundaerKlassifikasjon.  Hvorfor kan en ikke gjøre det samme for registreringer?  Spesielt for fasettert klassifikasjon basert på emneord vil det være nyttig å kunne klassifisere registreringer og journalposter for senere søk.  Hva med å tillate valgfri kobling av flere M209 referanseSekundaerKlassifikasjon til registrering (eventuelt journalpost) med forekomst 0..M?  Hvis det tillates for registrering, så gir det mening å tillate tilsvarende for mappe, det vil si å flytte M209-elementet fra saksmappe til mappe.  Konkret trengs det endring i tillegg A (Metadatakatalog) og B (Metadata gruppert på objekter).

**Comment by monadani** [comment]
Høres fornuftig ut.

**Comment by oivkru** [comment]
Enig i at det er fornuftig å gjøre dette. Men er det fortsatt behov for å gjøre dette hvis vi (i Noark 5 versjon 6, for eksempel) tar klassifikasjon og klasse ut av den hierarkiske arkivstrukturen og sier at _klasse_ kan ha 0-M klasser og/eller registreringer, og at både mapper og registreringer kan tilhøre 0-M klasser? 

Hvis vi gjør dette er det allikevel mulig at ett klassifikasjonssystem må defineres som primært, slik at resten er sekundære, for at vi skal kunne styre arv av bevaring og kassasjon, jf. issue #34 

Kanskje dette som @petterreinholdtsen foreslår er en midlertidig, mindre fiks, i påvente av et større grep i neste hovedversjon?

**Comment by petterreinholdtsen** [comment]
[Øyvind Kruse]
> Enig i at det er fornuftig å gjøre dette.

Godt.  Laget endringsforslag #97 som gjennomfører endringen.

> Men er det fortsatt behov for å gjøre dette hvis vi (i Noark 5 versjon
> 6, for eksempel) tar klassifikasjon og klasse ut av den hierarkiske
> arkivstrukturen og sier at _klasse_ kan ha 0-M klasser og/eller
> registreringer, og at både mapper og registreringer kan tilhøre 0-M
> klasser?

Slik jeg forstår det vil det være nødvendig med tilsvarende endring også
i dette tilfellet, men navnet på referanseSekundaerKlassifikasjon blir
kanskje litt misvisende og burde hete referanseKlassifikasjon eller noe
slikt i dette tilfellet.

> Hvis vi gjør dette er det allikevel mulig at ett klassifikasjonssystem
> må defineres som primært, slik at resten er sekundære, for at vi skal
> kunne styre arv av bevaring og kassasjon, jf. issue #34

Det kommer vel an på hvordan arv til slutt beskrives for å løse #34, men
det høres rimelig ut å gjøre det klart hva som arver og hva som ikke
gjør det.

-- 
Vennlig hilsen
Petter Reinholdtsen
