### ISSUE TITLE
Skal M104 mottattDato ha med klokkeslett?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#41]
I tillegg B så er M104 ført opp som dato uten klokkeslett, mens i XSD og Tjenestegrensesnitt er den ført opp med klokkeslett.

Skal disse oppføringene synkroniseres slik at M104 har samme datatype over alt? I så fall, hvilken datatype skal brukes?

**Comment by monadani** [comment]
JA
