### ISSUE TITLE
Skal M105 sendtDato ha med klokkeslett?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#42]
I tillegg B så er M105 ført opp som dato uten klokkeslett, mens i XSD og Tjenestegrensesnitt er den ført opp med klokkeslett.

Skal disse oppføringene synkroniseres slik at M105 har samme datatype over alt? I så fall, hvilken datatype skal brukes?

**Comment by monadani** [comment]
JA
