### ISSUE TITLE
Skal M622 verifisertDato ha med klokkeslett?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#43]
I tillegg B så er M622 ført opp som dato med klokkeslett, mens i XSD og Tjenestegrensesnitt er den ført opp uten klokkeslett.

Skal disse oppføringene synkroniseres slik at M622 har samme datatype over alt? I så fall, hvilken datatype skal brukes?

**Comment by monadani** [comment]
JA
