### ISSUE TITLE
Undertitler bør merkes som RST-overskrifter

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#5]
Omformingen har kun fått med seg at noen av overskriftene er overskrifter.  En bør gå igjennom hele teksten å merke opp alle overskrifter med riktig RST-nivå.

**Comment by AnnKnu** [comment]
Enig, det bør fikses

**Comment by petterreinholdtsen** [comment]
Jeg har gått igjennom vedlegg 1-3 og fikset overskrifter der (trengte de til automatisk uthenting av metadatainformasjon).  Håper det ble riktig.

**Comment by petterreinholdtsen** [comment]
@AnnKnu Hvordan går det med oppdatering av overskrifter.  Er det noe uklart om hvordan det skal gjøres, som jeg kan bidra med å finne ut av?

**Comment by AnnKnu** [comment]
Nei @petterreinholdtsen  har bare ikke hatt kapasitet/tid.

**Comment by AnnKnu** [comment]
Jeg foreslår 
1. Heading 1
#########

1.1 Heading 2
==========

1.1.1 Heading 3
---------------------

Heading 4 
~~~~~~~~~~~~

**Comment by petterreinholdtsen** [comment]
For overskrifter foreslår jeg at de fire første nivåene av overskrifter bruker '=', '-', '~' og '*' i den rekkefølgen.  Så langt har vi kun brukt tre nivåer.

Eksempel:
```
Kapittel
========

Undernivå 1
-----------

Undernivå 2
~~~~~~~~~~

Undernivå 3
***********
```

**Comment by petterreinholdtsen** [comment]
Har noen en ide når overskriftene vil være sjekket/fikset?

**Comment by petterreinholdtsen** [comment]
Jeg oppdaget og fikset endel tabeller som ikke lenger ble gjenkjent som tabeller.  Årsaken var nye overskrifter uten tom linje forran og bak, som noen gangern ble misforstått til å være del av foregående avsnitt, og noen ganger gjorde at to tabeller ble oppfattet som en feilformattert stor tabell.  Det er altså lurt å legge inn linjeskift forran og bak overskrifter.

Fant forresten endel overskrifter som muligens er tiltenkt å være tabell-beskrivelser.  Si i fra hvis det er tilfelle, så kan jeg rykke inn tabellene og gi dem tilkoblet beskrivelse.

**Comment by petterreinholdtsen** [comment]
Jeg mistenker denne kan anses løst.  Forslag til endring av overskrifter til bildebeskrivelser er i #15.  Tabell-beskrivelser er allerede omformet i master.

**Comment by AnnKnu** [comment]
> Jeg mistenker denne kan anses løst. Forslag til endring av overskrifter til bildebeskrivelser er i #15. Tabell-beskrivelser er allerede omformet i master.
