### ISSUE TITLE
Legg til endret* til arkivenheter?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#55]
I Noark 5 Tjenestegrensesnitt arver flere entiteter informasjon om sist endring fra en baseentitet ved navn Arkivenhet.  Dette gjelder endretDato, endretAv og referanseEndretAv (tidligere het tilsvarende felter *oppdatert* i tjenestegrensesnittet).  Det hadde vært fint om denne informasjonen kom med i en avleveringspakke. Det ville gjøre det mulig å se på hvert enkelt instans om den ble endret etter oppretting eller om den har vært urørt.

I tjenestegrensesnitt-spesifikkasjonen gjelder dette entitetene Arkiv, Arkivdel, Arkivskaper, Dokumentbeskrivelse, Dokumentobjekt, Klasse, Klassifikasjonssystem, Kryssreferanse, Mappe og Registrering.

I dagens Noark 5 er informasjon om siste endring for endel entiteter tilgjengelig i endringsloggen, der feltene endretDato (M682) og endretAv (M683) finnes allerede.  Det er dog ikke krav om loggføring av alle endringer i entitetene, slik at entiteten kan være oppdatert uten at det finnes en loggoppføring.

Dette er relatert til mangelmelding https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/issues/255 for tjenestegrensesnittet.

Jeg foreslår at det legges inn et avsnitt i kapittel 2 om valgfrie felter om sist endret og av hvem, et nytt attributt i tillegg A (Metadatakatalog) og nye attributter i aktuelle entiteter i tillegg B (Metadata gruppert på objekter).

**Comment by hanber** [comment]
Siden *oppdatert* bare finnes i tjenestegrensesnittet, mens endret* er definert i metadatakatalogen, synes jeg vi skal endre dette til *endret* i tjenestegrensesnittet. Jeg mener dette med fordel kan ligge i den abstrakte klassen "abstraktarkivenhet" i tjenestegrensesnittet. Siden denne ikke finnes i arkivstruktur.xsd, bør de legges inn i alle arkivenhetene i datamodellen for Noark 5. - Hvis vi da ikke skal ta skrittet fullt ut og innføre "arkivenhet" som en superklasse for arkivenhetene i Noark 5.

Jeg synes videre at den abstrakte arkivenheten skal hete "arkivenhet", ikke "abstraktarkivenhet". Dersom "abstraktarkivenhet" skal beholdes bør den hete "abstraktArkivenhet" i henhold til våre skriveregler.

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Siden *oppdatert* bare finnes i tjenestegrensesnittet, mens endret* er
> definert i metadatakatalogen, synes jeg vi skal endre dette til
> *endret* i tjenestegrensesnittet.

Godt, da er vi enig der. :)

> Jeg mener dette med fordel kan ligge i den abstrakte klassen
> "abstraktarkivenhet" i tjenestegrensesnittet. Siden denne ikke finnes
> i arkivstruktur.xsd, bør de legges inn i alle arkivenhetene i
> datamodellen for Noark 5. - Hvis vi da ikke skal ta skrittet fullt ut
> og innføre "arkivenhet" som en superklasse for arkivenhetene i Noark
> 5.

Kan du fortelle hvor du ser 'abstraktarkivenhet' i tjenestegrensesnittet?
Jeg finner det ikke, det eneste jeg finner er 'arkivenhet' i kapittel 7.

> Jeg synes videre at den abstrakte arkivenheten skal hete "arkivenhet",
> ikke "abstraktarkivenhet". Dersom "abstraktarkivenhet" skal beholdes
> bør den hete "abstraktArkivenhet" i henhold til våre skriveregler.

Helt enig. :)

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
I [noark5-tjenestegrensesnitt-standard/xsd/arkivstruktur.xsd](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/blob/master/xsd/arkivstruktur.xsd).

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> I [noark5-tjenestegrensesnitt-standard/xsd/arkivstruktur.xsd](https://github.com/arkivverket/noark5-tjenestegrensesnitt-standard/blob/master/xsd/arkivstruktur.xsd).

Aha.  Aner ikke hva filene i XSD-katalogen i git-repoet er tenkt brukt
til, men de har ingen rolle i spesifikasjonen av
tjenestegrensesnitt-API-et, så vidt jeg vet.  Der er det den tekstlige
beskrivelsen av JSON-strukturer i kapitler/*.rst som gjelder.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Jeg har lagt til M200 referanseOpprettetAv, M201 referanseAvsluttetAv og M204 referanseEndretAv som yaml-filer, og erstattet oppdatert med endret i 07-tjenester_og_informasjonsmodell.rst.

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Jeg har lagt til M200 referanseOpprettetAv, M201 referanseAvsluttetAv
> og M204 referanseEndretAv som yaml-filer, og erstattet oppdatert med
> endret i 07-tjenester_og_informasjonsmodell.rst.

Ypperlig.  Jeg har utledet 110-vedlegg_1_metadatakatalog-auto.rst fra
det oppdaterte innholdet i metadata/ og sjekket inn endringen.  (Det
gjøres enklest med 'make kapitler/110-vedlegg_1_metadatakatalog-auto.rst').

Er det meningen å introdusere ny undertittel "Logging av endringer" i
tillegg A?  Alle andre i 200-serien har gruppe 'Referanser'.

Har M200, M201 og M204 blitt brukt tidligere?  Hvis ikke, hvorfor hoppet
en over dise nummerene tidligere og startet med M202, M203, M208 i
200-serien?

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Jeg har ikke tenkt å introdusere noen ny gruppe, vi beholder "Referanser"  for 200-serien.

Jeg lurte også på om numrene har vært brukt tidligere, men antok at det bare var noen ubrukte for fremtidig bruk. Når du nå først spør om det, skal jeg grave litt i historien.

**Comment by hanber** [comment]
Jo, de fantes i Noark 5 versjon 1. Da synes jeg vi skal unngå å bruke dem, og kanskje legge inn de numrene som mangler og markere dem som utgått. Det beste hadde vært å lage YAML-filer for dem og merke dem som utgått. Noen av dem har det også vært på tale å gjeninnføre.

Har du et script som tar metadatakatalogen i Word og lager YAML-filer, eller skal jeg eventuelt legge dem inn manuelt?

Numrene fra og med 225 ser ut til å være ubrukte.

Jeg fikser det senere i dag.

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Har du et script som tar metadatakatalogen i Word og lager YAML-filer,
> eller skal jeg eventuelt legge dem inn manuelt?

Programmet scripts/metadatarst2yaml omformer fra rst til YAML.
Omforming fra docx til rst ble gjort med pandoc, se regelen docx-to-rst
i Makefile.  Jeg er ikke sikker på om det ble gjort manuell rydding i
rst-filene mellom docx-to-rst og kjøring av metadatarst2yaml.

Jeg ville gjort et forsøk og sett om resultatet ble bra, og hvis ikke
gjort omformingen manuelt.  Merk at metadatarst2yaml omformer hele
tillegg A, slik at det nok vil følge med uønskede endringer i andre
YAML-filer som ikke bør sjekkes inn.
-- 
Vennlig hilsen
Petter Reinholdtsen
