### ISSUE TITLE
systemID mangler på part og korrespondansepart

### ISSUE THREAD

**Issue by monadani** [arkivverket/noark5-standard#65]
systemID mangler på part og korrespondansepart, må tas med i N 5.5.1

**Comment by petterreinholdtsen** [comment]
Relatert i så måte er https://github.com/arkivverket/schemas/issues/21 .

**Comment by SteinarAbrahamsen** [comment]
Det er krav om sakspart og korrespondansepart skal tildeles en system id i NOARK 5 tjenestegrensesnittet versjon 1.0.

Hva ønsker arkivverket at NOARK-5 spesifikasjonen skal være: En spesifikasjon for hvordan data skal avleveres eller utveksles? Flere av problemstillingene som oppstod ved utredning av tjenestegrensesnittet oppstod fordi en skjelte til metadatakatalogen i NOARK-5 som primært var laget for avlevering av data.  Hovedmålet var å innordne objektene i en hierarkisk nøstet struktur.

Et eksempel: I Noark tjenestegrensenittet må en opprette to kryssreferanser for å opprette en to-veis lenke. Her burde en kunne opprettet en -1- kryssreferanse med til og fra verdier.  Årsaken til at det ble slik var kryssreferanser var gruppert inn under mappe, registrering i avleveringsformatet (NOARK-5) og den ene verdien var således gitt.

**Comment by SteinarAbrahamsen** [comment]
Problem
I Noark 5 versjon 5 krav 2.2.2 er det fremsettes det krav om at arkivenhet som dupliseres skal tildeles en unik id slik at identiske enheter skal tildeles **ulike** systemid'er.  En Dokumentbeskrivelse kan være tilknyttet flere registreringer. Dette innebærer at en Dokumentbeskrivelse kan ha flere system id'er.  Dette av hensyn til hierarkiske strukturen som er ønsket i en avleveringspakke. 
Forslag til løsning
En Dokumentbeskrivelse bør tildeles en -1- systemid som følger Dokumentbeskrivelsen gjennom hele livsløpet. Denne system id vil da kunne brukes for å sikre interoperabilitet og entydig identifisering av objektet. 

Jeg kan åpne en ny issue for kryssreferanse slik at denne kan være to-veis og opereres som et selvstendig objekt uavhengig av innplassering i den hierarkiske strukturen.

**Comment by petterreinholdtsen** [comment]
Noark 5 Tjenestegrensesnitt har avskriving.referanseAvskrivesAvKorrespondansepart i tillegg til avskriving.referanseAvskrivesAvJournalpost (M215), og sistnevnte er så vidt jeg forstår ment å peke til hvilken mottaker av referert journalpost som fører til at henvendelsen er avskrevet.  referanseAvskrivesAvKorrespondansepart mangler i Noark 5, men for å kunne referere til bestemte korrespondanseparter trenger sistnevnte en ID som kan legges inn i referanseAvskrivesAvKorrespondansepart.
