### ISSUE TITLE
Hvor er vedlegg 4?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#7]
Versjonen som kom ut i desember har vedlegg 3 og 5, men ikke 4.  Ble dette vedlegget droppet i overgangen fra versjon 4 til 5?

**Comment by AnnKnu** [comment]
@petterreinholdtsen  ja eksempel på virksomhetsspesifikke metadata ble droppet i 5.5.0

**Comment by petterreinholdtsen** [comment]
For å beholde vedleggsnummereringen lager vi et fyllstoff-vedlegg som får nummer 4 og forklarer at dette vedlegget ble droppet i nummer 5.5.0.
