### ISSUE TITLE
Dokumentasjonen i PDF må ha bokmerker for navigasjon

### ISSUE THREAD

**Issue by sturtzel** [arkivverket/noark5-standard#71]
For å lette bruken av denne er det ønskelig at innholdsfortegnelsen legges ut som bokmerker i PDF-en. Dette skjer automatisk ved produksjon via Adobe plugin i Word, men ikke hvis den lages via utskriftsfunksjon.

Sett gjerne også navigasjonskategori til Bokmerkepanel og side under Standardvisning i dokumentegenskapene. Da kan man klikke i venstrekanten for å gå direkte til forskjellige kapitler i dokumentet.

**Comment by hanber** [comment]
Kan du få til det, @petterreinholdtsen?

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Kan du få til det, @petterreinholdtsen?

Snakker vi her om PDF-utgaven av Noark 5-spesifikasjonen?  I så fall
skal jeg se hva dblatex kan få til.  Hvis ikke antar jeg vi snakker om
krav til PDF-er som skal avleveres, og der har jeg ikke noe syn på
saken.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by sturtzel** [comment]
Ja, vi snakker om spesifikasjonsdokumentene, spesielt hoveddokumentet. Men gjerne også vedleggene selv om jeg ser at det er litt mer jobb siden det ikke er benyttet overskriftsstiler i de.

**Comment by tsodring** [comment]
Hei,
Når jeg åpner standarden (avledet/spesifikasjon.pdf) i Adobe reader på Windows ser jeg følgende:

![image](https://user-images.githubusercontent.com/1899412/100612859-e8ea5a80-3313-11eb-8675-6f1315676524.png)

Det ser jo ut som om innholdsfortegnelsen er bokmerker der. Er det noe jeg misforstår her?

**Comment by sturtzel** [comment]
Har du da hentet fra https://www.arkivverket.no/forvaltning-og-utvikling/noark-standarden/noark-5/noark5-standarden?

Jeg får tom liste over bokmerker ved nedlasting derfra.

**Comment by tsodring** [comment]
Nei, Jeg henter fra [fra](https://github.com/arkivverket/noark5-standard/blob/master/avledet/spesifikasjon.pdf). Hmm. Det ser jo ut som om den du refererer til ikke kommer for github. Denne må tilbake til @hanber.

**Comment by sturtzel** [comment]
Flott! Da er saken løst. Jeg har alltid lastet ned standarden fra hjemmesiden.

Ja, jeg vet at man ikke får vist bokmerkene i nettleseren, det er ikke noe problem.

**Comment by tsodring** [comment]
Når du sier:

`er innholdsfortegnelsen død, `

Har du prøvd å trykke på tallene. Kapitteltittel er 'død' men tallene skal du kunne trykke på.

**Comment by hanber** [comment]
Det visste jeg ikke. Jeg prøvde nå, men det gikk ikke. Jeg får heller ingen "pekefinger-hånd" når jeg peker på tallene.

**Comment by tsodring** [comment]
Jeg burde vært mer presis - det skal være mulig å trykke på sidetallet, ikke titteltallet, i innholdsfortegnelsen.

![image](https://user-images.githubusercontent.com/1899412/100627656-8a2edc00-3327-11eb-8f9c-512184e61aa9.png)

Jeg har sjekket at dette fungerer under adobe reader på windows også.

**Comment by hanber** [comment]
Det var det jeg prøvde, det fungerer med den nedlastede fila, både når den vises i Chrome og i Acrobat Reader, men ikke i visningen i Github (i nettleser). Takk for oppklaringene, da tillater jeg meg å lukke denne saken.
