### ISSUE TITLE
Arbeidsgruppe for ny Geointegrasjon Arkiv 2.0 vil gi innspill, disse er ikke klar før ca. 20.10

### ISSUE THREAD

**Issue by harhus** [arkivverket/noark5-standard#72]
Gjennnom hele 2020 har en arbeidsgruppe jobbet med ny standard for Geointegrasjon Arkiv 2.0, som skal erstatte dagens Geointegrasjon 1.1. Den nye standarden er basert på bruk av FIKS IO fra KS, og skal være ferdig til 20.10. 
**Vi vil bruke arkivmeldingen til å overføre data i grensesnittet og legger til grunn at alle felt vi trenger i arkivmeldingen bør inn i NOARK.**
Vi vil levere en liste over disse innen 20.10.

På vegne av arbeidsgruppa
Harald Huse, Norkart - leder/sekretær.

**Comment by hanber** [comment]
Det kommer en tilbakemelding fra arbeidsgruppa i uke 49 (59)

**Comment by sturtzel** [comment]
Det er forberedt og behandles i arbeidsgruppen i morgen. Kommer vi ikke helt i mål da blir det en runde til om en uke.
