### ISSUE TITLE
Mal for beskrivelse metadataelement

### ISSUE THREAD

**Issue by hanber** [arkivverket/noark5-standard#73]
Lages slik at den kan importeres rett inn i en YAML-fil.

**Comment by hanber** [comment]
Jeg har laget utkast til mal for registrering av forslag til nye metadata eller endring av eksisterende på https://github.com/arkivverket/noark5-standard/blob/master/.github/ISSUE_TEMPLATE/metadataforslag.md.

Den er ikke slik at den kan importeres direkte inn i YAML-filer fordi jeg syntes de enkelte elementene trengte forklarende tekst, og vi må uansett gå gjennom dem, og ganske sikkert redigere dem før det lages YAML-fil av dem.

Jeg vet ikke hvordan jeg får til å la egenskapen stå som en ledetekst, slik at man kan fylle inn tekst etter egenskapen. @petterreinholdtsen , Kan du hjelpe til med det?

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Jeg har laget utkast til mal for registrering av forslag til nye
> metadata eller endring av eksisterende på
> https://github.com/arkivverket/noark5-standard/blob/master/.github/ISSUE_TEMPLATE/metadataforslag.md.

Ah, hurra.  Merk en liten skrivefeil, 'Metadatforslag'.

> Den er ikke slik at den kan importeres direkte inn i YAML-filer fordi
> jeg syntes de enkelte elementene trengte forklarende tekst, og vi må
> uansett gå gjennom dem, og ganske sikkert redigere dem før det lages
> YAML-fil av dem.

Enig.

> Jeg vet ikke hvordan jeg får til å la egenskapen stå som en ledetekst,
> slik at man kan fylle inn tekst etter egenskapen. @petterreinholdtsen,
> Kan du hjelpe til med det?

Bidrar gjerne hvis jeg kan , men forstår ikke spørsmålet.  Merk, jeg er
ikke veldig erfaren med github-mangelmeldingsmaler, så det er ikke
sikkert jeg har mye å bidra med. :)

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Jeg ville gjerne at malen skulle se omtrent slik ut:
Nr: _Mxxx (dersom det er forslag til endring av eksisterende metadataelement)_
Navn: _Navn på elementet i henhold til skriveregler nedenfor_
Definisjon: _Presis definisjon av metadataelementet_
osv.

Der ledetekstene ("Nr: ", "Navn: " og "Definisjon: ") står fast og ikke kan overskrives, mens forklaringene (i kursiv) overskrives med de aktuelle verdiene. Skrivemerket plasseres etter ledetekstene når man klikker på linja. Det beste hadde vært om det som står i kursiv forsvinner når man setter skrivemerket på linja, slik det ofte er i "moderne" skjemaløsninger.

Jeg kan eventuelt lage en tabell hvor ledetekst med forklaring er i første kolonne, og andre kolonne er for innfylling. Et elternativ er at første kolonne inneholder ledeteksten, andre kolonne inneholder forklaringen, og at jeg i den innledende teksten skriver at den som legger inn elementet overskriver forklaringen.

Hva tror du?

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Hva tror du?

Jeg tror jeg forstår hva du vil ha.  Jeg tror du vil ha et webskjema der
feltnavn er låst og brukeren skal fylle inn verdier tilhørende disse
feltene.  Jeg aner ikke om det er mulig.  Men la oss se hva jeg kan
finne...

Fant
<URL: https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates >
og lette litt rundt der, uten å bli klokere.  Er ikke sikker på om det
du ønsker er mulig med malsystemet til github, har aldri gjort det selv,
bare lagt inn en markdown-mal som brukeren kunne redigere fritt før
innsending.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by hanber** [comment]
Det er helt riktig. Ikke legg for mye arbeid i det. Jeg prøver å lage en tabell. Takk uansett.
