### ISSUE TITLE
Bør tabell 1.1 avslutte setninger med punktum?

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#83]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Standard
           Kategori  Noark 5.5.0
    Brukerreferanse  pere@hungry.com
        Dokumentdel  1.4
         Sidenummer  6
        Linjenummer  205
 ------------------  ---------------------------------

### Beskrivelse

Oppføringene i tabell 1.1 har ikke avsluttende punktum.  Det ser litt merkelig ut, og jeg mistenker de burde hatt punktum på slutten.

## Ønsket endring

Bruk avsluttende punktum på innholdet i tabellen.

**Comment by hanber** [comment]
Bruk avsluttende punktum.

**Comment by petterreinholdtsen** [comment]
Dette ble korrigert i a5e8adde1ec57a095dde7beebe6852ace223a79a.
