### ISSUE TITLE
Endre navn fra punkt til posisjon

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#92]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Standard
           Kategori  Noark git 2021-03-19
    Brukerreferanse  pere@hungry.com
        Dokumentdel  B.2.13
         Sidenummer  209
        Linjenummer  1972
 ------------------  ---------------------------------

Overført fra https://github.com/arkivverket/noark5-standard/issues/77 .

### Beskrivelse

Som del av introduksjon av nasjonale identifikatorer har en lagt til 'punkt' som en datatype.  Denne bør bytte navn til posisjon for å bruke sammen navn som i Noark 5 Tjenestegrensesnitt og i Matrikkelen.

## Ønsket endring

Endre bruken av punkt med posisjon der den er brukt, dvs. i filene

* kapitler/120-vedlegg_2_metadatakatalog_objektsortert.rst
* metadata/M040.yaml
* metadata/M041.yaml
* metadata/M042.yaml
* metadata/M043.yaml

**Comment by hanber** [comment]
Da både tjenestegrensesnittet og Matrikkelen bruker posisjon (jf. også siste innlegg i #77), gjør vi det óg. Jeg endrer i de aktuelle filene.
