### ISSUE TITLE
Endre YAML-feltnavn 'X' til 'Gjeldende'

### ISSUE THREAD

**Issue by petterreinholdtsen** [arkivverket/noark5-standard#95]
------------------  ---------------------------------
           Prosjekt  NOARK 5 Standard
           Kategori  Noark 5.5.0
    Brukerreferanse  pere@hungry.com
 ------------------  ---------------------------------

### Beskrivelse

Dagens YAML-filer har et bolsk felt 'X' som styrer om M-verdien skal være med i avledet RST-fil og dermed i spesifikasjonsteksten eller ikke.  Hvis det er 'true', så blir metadatakatalogoppføringen med i spesifikasjonen.  'X' ble valgt da vi ikke kom på et godt ord å bruke som feltnavn da systemet for å utelukke utdaterte metadatakatalogoppføringer, med intensjon om å bytte navn senere.

Jeg foreslår å bytte navn på feltet fra 'X' til 'Gjeldende' eller 'Utrangert' (med motsatt logikk av i dag).

## Ønsket endring

Bytt 'X:' til 'Gjeldende:' i alle yaml-filer, og endre 'X' i scripts/metadata2rst.

**Comment by hanber** [comment]
Enig, dvs. bruk «Gjeldene». Kan du gjøre en gjennomgående substitusjon?

**Comment by petterreinholdtsen** [comment]
[Hans Fredrik Berg]
> Enig, dvs. bruk «Gjeldene». Kan du gjøre en gjennomgående
> substitusjon?

Ja, det fikser jeg raskt.

Kan det forresten være en ide å i stedet for en bolsk verdi, ha et
datofelt som forteller når metadatakatalogoppføringen ble 'Utfastet'?
Da kan vi sammenligne med dagens dato og enklere se når ulike felter ble
faset ut, og vite hvor lenge siden det er et felt ble brukt?  Merk, Det
er i dag i git ikke er noen M-verdier der X = false.  Det burde det
kanskje vært.

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
[Petter Reinholdtsen]
> Kan det forresten være en ide å i stedet for en bolsk verdi, ha et
> datofelt som forteller når metadatakatalogoppføringen ble 'Utfastet'?
> Da kan vi sammenligne med dagens dato og enklere se når ulike felter ble
> faset ut, og vite hvor lenge siden det er et felt ble brukt?  Merk, Det
> er i dag i git ikke er noen M-verdier der X = false.  Det burde det
> kanskje vært.

Jeg tenkte det var greit å få svar på dette før jeg gjorde endringen.
Var det feil tenkt?

-- 
Vennlig hilsen
Petter Reinholdtsen

**Comment by petterreinholdtsen** [comment]
Basert på responsen sjekket jeg inn i master endringen X->Gjeldende, og laget et endringsforslag #106 for å ta steget videre til datobasert Utdatert-felt som gjør det mulig å notere når en oppføring ble tatt ut av spesifikasjonen.
